env:
  - LeetABit_Build_Verbose=1 LeetABit_Build_ForceInstallPowerShell=1

jobs:
  include:
  - os: windows
    language: shell
    script: ./run.cmd help
  - os: linux
    language: shell
    dist: focal
    script: ./run.sh help
  - os: linux
    language: shell
    dist: bionic
    script: ./run.sh help
  - os: linux
    language: shell
    dist: xenial
    script: ./run.sh help
  - os: linux
    language: shell
    dist: trusty
    script: ./run.sh help
  - os: linux
    language: shell
    arch: arm64
    script: ./run.sh help
  - os: osx
    language: shell
    osx_image: xcode12.2
    script: ./run.sh help
  - os: osx
    language: shell
    osx_image: xcode11.6
    script: ./run.sh help
  - os: osx
    language: shell
    osx_image: xcode10.3
    script: ./run.sh help
  - os: osx
    language: shell
    osx_image: xcode9.4
    script: ./run.sh help
  - os: osx
    language: shell
    osx_image: xcode8.3
    script: ./run.sh help