name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  LeetABit_Build_Verbose: 1
  LeetABit_Build_ForceInstallPowerShell: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15 ]

    steps:
    - uses: actions/checkout@v2

    - name: Run CMD
      if: matrix.os == 'windows-2019'
      run: ./run.cmd help
      
    - name: Run Bash
      if: matrix.os != 'windows-2019'
      run: ./run.sh help
